// This file is auto-generated by @tanstack/router-vite-plugin
// Don't edit manually — run the dev server to regenerate

import { Route as rootRoute } from "./routes/__root.js";
import { Route as IndexRoute } from "./routes/index.js";
import { Route as SettingsRoute } from "./routes/settings.js";

export const routeTree = rootRoute.addChildren([IndexRoute, SettingsRoute]);
